apiVersion: apps/v1
kind: Deployment
metadata:
  name: route53-ddns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: route53-ddns
  template:
    metadata:
      labels:
        app: route53-ddns
    spec:
      containers:
        - name: route53-ddns
          image: unknownpgr/route53-ddns:latest
          imagePullPolicy: Always
          env:
            - name: RECORD
              value: "*.server.unknownpgr.com;*.unknownpgr.com;*.ction.link;univting.com;*.univting.com;*.ist.sh"
            - name: TTL
              value: "300"
          volumeMounts:
            - name: secret
              mountPath: "/root/.aws/config"
              subPath: config
              readOnly: true
          stdin: true
          tty: true
      volumes:
        - name: secret
          secret:
            secretName: route53
            optional: false
            items:
              - key: config
                path: config
